#!/usr/bin/python

import sys
import os
import jinja2

progname = os.path.basename(sys.argv[0])

try:
    rn_qa_dir = os.environ['RN_QA_DIR']
except KeyError:
    rn_qa_dir = None

if len(sys.argv) != 2:
    print
    print 'usage: %s <RN QA output directory>' % progname
    print
    if not rn_qa_dir:
        print 'warning: RN_QA_DIR not set'
        print
    sys.exit(0)

if not rn_qa_dir:
    sys.stderr.write('%s: RN_QA_DIR not set\n' % progname)
    sys.exit(1)

output_dir = sys.argv[1]

print 'jinja version %s' % jinja2.__version__

sys.exit(0)

# eof
